### ISSUE TITLE
"Each field could only be used once" issue

### ISSUE THREAD

**Issue by vootn** [ThoreBor/CC-CEDICT-for-Anki#26]
Hi, the add-on had been working just fine until I updated yesterday. Now everytime I add a card it won't work and says "Each field could only be used once". Do you know how to resolve this?

Thanks

**Comment by ThoreBor** [comment]
I'm sorry to hear that. Did you make sure that you use four different fields for the output? Could you maybe send a screenshot?

**Comment by vootn** [comment]
![Picture1](https://user-images.githubusercontent.com/90122843/132155520-3c20e85e-c926-4979-ae46-dc2b0536dcb6.png)
 I have tried different note templates and removed all other add-ons but none is working. Do know the reason for that?

**Comment by ThoreBor** [comment]
Alright, thanks. Could you also send me that error message?

**Comment by vootn** [comment]
![Picture2](https://user-images.githubusercontent.com/90122843/132191261-cda6edec-b584-4d38-8adf-40cd9153ae76.png)

**Comment by ThoreBor** [comment]
> ![Picture1](https://user-images.githubusercontent.com/90122843/132155520-3c20e85e-c926-4979-ae46-dc2b0536dcb6.png)
> I have tried different note templates and removed all other add-ons but none is working. Do know the reason for that?

Sorry, I meant the one on the left here. Just click on copy to clipboard and paste it here.

**Comment by vootn** [comment]
Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeat until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.44 (b2b3275f) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-09-06 16:05:58

Caught exception:
Traceback (most recent call last):
  File "C:\Users\VuNguyen\AppData\Roaming\Anki2\addons21\418828045\cedict\main.py", line 352, in init_add
    self.add_note([simp, trad, pinyin, english], input_type, tags)
  File "C:\Users\VuNguyen\AppData\Roaming\Anki2\addons21\418828045\cedict\main.py", line 277, in add_note
    n = col.new_note(nid)
AttributeError: 'Collection' object has no attribute 'new_note'

**Comment by ThoreBor** [comment]
> ![Picture1](https://user-images.githubusercontent.com/90122843/132155520-3c20e85e-c926-4979-ae46-dc2b0536dcb6.png)
> I have tried different note templates and removed all other add-ons but none is working. Do know the reason for that?

Thanks!
Did you also get the "Each field can only be used one" error here?

**Comment by vootn** [comment]
No that notification shows when I choose templates without less that 4 fields. Before having this problem I never had to choose any template, I just had to find a word and add them to the Deck.

**Comment by ThoreBor** [comment]
Okay, that's not the problem then. You'll need four fields for this to work. The other issue is, that I didn't realize, that this add-on won't work with older Anki versions. Could you test if this fixes the problem? Just download the .ankiaddon file and open it to install it:
https://drive.google.com/file/d/1VYMWCo8TMr8cdhNTGqhGSVP54k3ipsES/view?usp=sharing

**Comment by vootn** [comment]
It still does not work. Do I need to install a newer Anki version?

// Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeat until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.44 (b2b3275f) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-09-06 16:05:58

Caught exception:
Traceback (most recent call last):
  File "C:\Users\VuNguyen\AppData\Roaming\Anki2\addons21\418828045\cedict\main.py", line 356, in init_add
    self.add_note([simp, trad, pinyin, english], input_type, tags)
  File "C:\Users\VuNguyen\AppData\Roaming\Anki2\addons21\418828045\cedict\main.py", line 303, in add_note
    n.add_tag(tags)
AttributeError: 'Note' object has no attribute 'add_tag'
//

**Comment by vootn** [comment]
Ok I've just installed Anki 2.1.47 and it works now. Thanks for your support!:) Have a good day!!!

**Comment by ThoreBor** [comment]
Alright, I'll either try to update the add-on so it'll work with all 2.1 versions, or users will have to use v1.2 if they use an older Anki version. Thanks for reporting this!
